exclude: ".*snap$"
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
        exclude_types: [pem]
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        exclude: "^.*migrations.*$"
  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
        args: [--line-length=100, --safe]
        exclude: "^.*migrations.*$"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
      - id: mypy
        args: [--follow-imports=silent, --ignore-missing-imports]
        exclude: "^.*migrations.*$"
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
      - id: flake8
        additional_dependencies:
          [
            "flake8-blind-except",
            "flake8-comprehensions",
            "flake8-pep3101",
            "flake8-bugbear",
            "flake8-print",
            "flake8-debugger",
          ]
